variables:
  GIT_STRATEGY: clone

stages:
  - test

test_job:
  stage: test
  tags:
    - runner
  script:
    - hostname
    - packer validate -syntax-only -var-file=$CI_PROJECT_DIR/packer/vars.json $CI_PROJECT_DIR/packer/packer.json
    - terraform init $CI_PROJECT_DIR/terraform/
    - terraform validate $CI_PROJECT_DIR/terraform/
  only:
    - merge_requests